### PR TITLE
Api600 support for server hardware

### PR DESCRIPTION
**Pull request by soodpr**
### Description
Api600 support for server hardware

### Check List
- [x] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
  - [X] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [X] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by madhav-bharadwaj — DISMISSED** [review]
Looks good to me.

**Review by madhav-bharadwaj — DISMISSED** [review]
Looks good,

**Review by sijeesh — DISMISSED** [review]
LGTM,

Please remove ssl_enabled flag from example file.

**Review by madhav-bharadwaj — APPROVED** [review]

**Review by jyothisgm — APPROVED** [review]
LGTM

**Pull request merged**
