### PR TITLE
Chef Partner cookbook build badge

### PR DESCRIPTION
**Pull request by jsmartt**
### Description

Added the build badge per the new Chef Partner cookbook guide guidelines. This required us to ignore the .direnv in simplecov. I also fixed up the tests so they didn't output unwanted error messages.
### Issues Resolved

(none)
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [x] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by jsmartt** [comment]
@jjasghar , the last thing (assuming this passes now), is integrating this build into the PR process. If we're going to be posting the badge on the README, I think we'll want to verify it's passing before merging it. Travis reports back it's status on the PR, and I think it would be nice to do something similar here. Does the job automatically try to post a status back? If so, we can just set up the permissions accordingly.

Also, what kicks it off? It's been a few minutes now and I haven't seen a job start yet... I'd like to be able to start it

**Comment by jjasghar** [comment]
@russellseymour we should look into this.

**Comment by jsmartt** [comment]
Also, @jjasghar , is there any additional value provided by this build over our Travis build? I assumed that the partner program requirements stated we needed to include a badge **from Chef's Jenkins test infrastructure**, but if that's not the case, can we just put a badge up from the Travis build instead? They run the same tests...

It would just kinda stink to have to mange multiple builds, one of which we can make PRs to, but don't have real control over to fix things quickly, run builds at will, etc.

Travis badge: [Build Status](https://travis-ci.org/HewlettPackard/oneview-chef)

**Comment by jjasghar** [comment]
> Also, @jjasghar , is there any additional value provided by this build over our Travis build? I assumed that the partner program requirements stated we needed to include a badge from Chef's Jenkins test infrastructure, but if that's not the case, can we just put a badge up from the Travis build instead? They run the same tests...

Good question. In order for us to integration tests for other cookbooks we needed to standardize on a build system. If you want, you can remove your travis tests; but for us we are going to be validating via our Jenkins build.

If you see though: https://travis-ci.org/HewlettPackard/ilo-chef/jobs/166815356 and https://jenkins-01.eastus.cloudapp.azure.com/job/ilo-cookbook/101/console show that things aren't pin correctly? 

After reading this, I feel like i'm not getting my point across. Can we sync on a Zoom in the near future?

**Comment by jsmartt** [comment]
Definitely! I'll be out of the office this morning, but free all afternoon. (and available tomorrow afternoon as well)

**Comment by jjasghar** [comment]
I'm in EMEA this week, but next week i'll be around. I'll send an invite out next week.

**Comment by jsmartt** [comment]
Sounds good! Thanks JJ :smile:

**Comment by hdiomede** [comment]
:+1:

**Pull request merged**
