### PR TITLE
Raise error after failed retrieve

### LINKED ISSUE #220: Resources continue after failed retrieve!
### Scenario/Intent
**Many** resource providers don't use `retrieve!` correctly. They will continue even after the retrieval fails.

### Environment Details
 - **oneview Cookbook Version:** 2.1.0

### Steps to Reproduce
There are quite a few resources that fit this bug, but one particular one is [enclosure_provider](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/resource_providers/api200/enclosure_provider.rb#L38). Try to run the `:reconfigure` or `:refresh` actions on a non-existent enclosure.

### Expected Result
Fail telling me the resource doesn't exist/wasn't found.

### Actual Result
It'll fail later on in the execution, often at a place that's hard to determine the real issue from.

### Affected Resource Providers:
This list may not be complete or entirely accurate, but based on a quick grep search (`grep -r 'retrieve!' libraries/resource_providers/ | grep -v 'raise'`), I got the following files to verify/fix:

- [ ] [libraries/resource_providers/api200/managed_san_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/managed_san_provider.rb)
- [ ] [libraries/resource_providers/api200/interconnect_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/interconnect_provider.rb)
- [ ] [libraries/resource_providers/api200/server_profile_template_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/server_profile_template_provider.rb)
- [ ] [libraries/resource_providers/api200/ethernet_network_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/ethernet_network_provider.rb)
- [ ] [libraries/resource_providers/api200/server_hardware_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/server_hardware_provider.rb)
- [ ] [libraries/resource_providers/api200/storage_pool_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/storage_pool_provider.rb)
- [ ] [libraries/resource_providers/api200/storage_system_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/storage_system_provider.rb)
- [ ] [libraries/resource_providers/api200/logical_enclosure_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/logical_enclosure_provider.rb)
- [ ] [libraries/resource_providers/api200/datacenter_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/datacenter_provider.rb)
- [ ] [libraries/resource_providers/api200/rack_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/rack_provider.rb)
- [ ] [libraries/resource_providers/api200/firmware_driver_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/firmware_driver_provider.rb)
- [ ] [libraries/resource_providers/api200/switch_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/switch_provider.rb)
- [ ] [libraries/resource_providers/api200/enclosure_group_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/enclosure_group_provider.rb)
- [ ] [libraries/resource_providers/api200/network_set_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/network_set_provider.rb)
- [ ] [libraries/resource_providers/api200/volume_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/volume_provider.rb)
- [ ] [libraries/resource_providers/api200/logical_interconnect_provider.rb](../tree/v2.1.0/libraries/resource_providers/api200/logical_interconnect_provider.rb)
- [ ] [libraries/resource_providers/api300/synergy/fabric_provider.rb](../tree/v2.1.0/libraries/resource_providers/api300/synergy/fabric_provider.rb)
- [ ] [libraries/resource_providers/api300/synergy/sas_interconnect_provider.rb](../tree/v2.1.0/libraries/resource_providers/api300/synergy/sas_interconnect_provider.rb)
- [ ] [libraries/resource_providers/api300/c7000/switch_provider.rb](../tree/v2.1.0/libraries/resource_providers/api300/c7000/switch_provider.rb)

### PR DESCRIPTION
**Pull request by jsmartt**
### Description
Fail immediately after a necessary retrieve fails. Also standardized the message across the board.

The 1 weird resource that I found (but didn't update) is in the [storage_system_provider](https://github.com/HewlettPackard/oneview-chef/blob/v2.1.0/libraries/resource_providers/api200/storage_system_provider.rb#L51). It returns after putting a log statement instead of failing, which seems very strange to me. @tmiotto or @fgbulsoni , do you know why it has this behavior? Should we fail like the other resources instead?

### Issues Resolved
Fixes #220

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by tmiotto** [comment]
Really weird  behavior in [storage_system_provider](https://github.com/HewlettPackard/oneview-chef/blob/v2.1.0/libraries/resource_providers/api200/storage_system_provider.rb#L51).

We should make it fail! :x:

**Review by tmiotto — COMMENTED** [review]
Seems fine :+1:

**Comment by jsmartt** [comment]
OK, @tmiotto , I agree about making it fail. Should I change that in this PR or a separate one? And is that a breaking change?

**Comment by tmiotto** [comment]
You can put in this one, I think it is the same issue this PR intends to fix.

Well, if you consider this PR a breaking change, so it is. But I guess it is not, it's just the correct behavior raising an exception instead throwing it on the error log.

**Comment by jsmartt** [comment]
I fixed the storage_system resource provider. Please verify

**Review by tmiotto — APPROVED** [review]
Great! :medal_sports:

**Pull request merged**
