### PR TITLE
API300 Server Profile

### LINKED ISSUE #159: Support Server Profile in API300
### Scenario/Intent
Add support to Server Profile in API300.

### Environment Details
 - **oneview Cookbook Version:** 1.1.0
 - **OneView Version:** 300

### PR DESCRIPTION
**Pull request by tmiotto**
### Description
Add support to Server Profile in API300.

### Issues Resolved
#159
#160     

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [x] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by jsmartt** [comment]
@tmiotto , I've added #162, which is related to this resource, but can probably be added in a separate PR. Just wanted to create that linkage

**Comment by tmiotto** [comment]
Uh oh.... it seems `chefspec` is breaking in Travis...

@jsmartt could you take a look at this? I could not find the root cause for this breakage.

**Comment by tmiotto** [comment]
It seems a general failure, [`master` is failing too](https://travis-ci.org/HewlettPackard/oneview-chef/builds/197030113), I'll open a issue for this.

**Comment by tmiotto** [comment]
See #163

**Comment by tmiotto** [comment]
@jsmartt I guess #162 could enter in another PR, it seems much more like a refactor, or new functionality with the existing code, this PR goal is more related to update the resource to API300.

**Comment by tmiotto** [comment]
It would make much more sense implementing the #160 right here, so I did it.

**Review by jsmartt — APPROVED** [review]

**Pull request merged**
