### PR TITLE
Synergy networks

### LINKED ISSUE #100: Synergy Networks
### Scenario/Intent
Add Synergy remaining networks support (FC, FCoE, Network Set)

They should be splitted into providers, the resources must be updated, but they haven't any new added features.

### PR DESCRIPTION
**Pull request by tmiotto**
### Description
Updates FC and FCoE networks, and also Network sets.

### Issues Resolved
#100

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by jsmartt — CHANGES_REQUESTED** [review]
A couple of notes:
- [ ] Please add these changes to the CHANGELOG
- [ ] Does this PR provide actual support for 3.0 on those resources? (i.e., have they been tested & verified?) Please say so in the CHANGELOG and/or PR description.
- [ ] As mentioned in #102 , I'm fine with just commenting out the [minimum coverage restrictions](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/spec_helper.rb#L10) for now.

**Comment by tmiotto** [comment]
That's some of my doubts.

Do we need to add these changes to the CHANGELOG? They were basically refactors to make de code look the new way.

Synergy support is basically following the Ruby SDK, that is not adding anything new to them. They were tested to see if they were working as expected, but they have no need to have unit tests since they are basically inheriting the API200 providers

**Comment by jsmartt** [comment]
I added a section the CHANGELOG for Ethernet Networks. If you'd rather not add it to ANY of the upcoming PRs, I'd suggest we remove that one too. As long as it's consistent. I'm fine either way, but would probably prefer adding it to the CHANGELOG so it's captured that we added official support for 3.0 on that resource. Currently I think we only **officially** support 2.0 on this cookbook, right?

**Review by jsmartt — APPROVED** [review]
👍

**Pull request merged**
