### PR TITLE
API 500 Support to FCoE Network

### LINKED ISSUE #254: Support to FCoE Network in API500
### Scenario/Intent
Add support to FCoE Network in API500.

### Environment Details
 - **oneview Cookbook Version:** unreleased next version (2.3.1)
 - **OneView API Version:** 500
 - **OneView Version:** 3.10

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Description
Support to FCoE Network in API500

### Issues Resolved
#254 
#94 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by tmiotto — DISMISSED** [review]

**Comment by ricardogpsf** [comment]
@tmiotto  @fgbulsoni Can you review again? Because I did put some other codes related to actions of scope (add_scope, remove_scope and replace_scopes).

**Comment by tmiotto** [comment]
Can you add the support required in #94 also?

**Comment by ricardogpsf** [comment]
Can you review @fgbulsoni @tmiotto @aalexmonteiro ? =)

**Comment by ricardogpsf** [comment]
We are using shared examples to test actions related to scopes (add_to_scopes, etc) and action related to reset_connection_template.

**Review by fgbulsoni — APPROVED** [review]
Looks good to me ✨

**Pull request merged**
