### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jjasghar**
### Description

Added the build badge per the new Chef Partner cookbook guide guidelines.

### CODE REVIEW

**Comment by tmiotto** [comment]
@jjasghar It added a badge saying the build is **failing**, but I can't see why the cookbook is failing to build.

Is that correct? Who is managing this Jenkins instance?

**Comment by jsmartt** [comment]
Looks like it's not doing a bundle install so can't find any necessary dependent libraries.

**Comment by jjasghar** [comment]
Yeah, we are dealling with some internal issues, updates when I have them.

Chef controls the instance and this'll be our continual certification.

**Comment by jjasghar** [comment]
Got it working again. Sorry about that :)

Can you take care of these errors? 

https://jenkins-01.eastus.cloudapp.azure.com/job/oneview-cookbook/104/console

**Comment by jsmartt** [comment]
@jjasghar, I don't think I have access to update the job config, but it needs to do a bundle install to download the dependent gems first. The iLO cookbook is having the same issues.

**Comment by jjasghar** [comment]
Huzzah! Sorry about that got it fixed.

Now it looks like there's been some updates to `rubocop` so you're failing on that.

I'll let you fix it per your coding standards, i'm here to help how i can.

https://jenkins-01.eastus.cloudapp.azure.com/job/ilo-cookbook/100/console

It looks like the oneview cookbook is actually failing on a real issue too 🤘 

https://jenkins-01.eastus.cloudapp.azure.com/job/oneview-cookbook/107/console

**Comment by hdiomede** [comment]
@jjasghar  the tests are not failing, we are raising an error if the resource was not found and we are catching it. I think the job is considering this as a failure.

**Comment by jjasghar** [comment]
@hdiomede i ran it locally and there are errors like:

```
================================================================================
Error executing action `set_public_attributes` on resource 'oneview_managed_san[ManagedSAN1]'
================================================================================

RuntimeError
------------
Resource not found: oneview_managed_san 'ManagedSAN1'

Cookbook Trace:
---------------
/var/folders/m_/whcml1ts22dbypfjlhnxjzrc0000gn/T/d20161011-23925-x4v49x/cookbooks/oneview/resources/managed_san.rb:56:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/folders/m_/whcml1ts22dbypfjlhnxjzrc0000gn/T/d20161011-23925-x4v49x/cookbooks/oneview_test/recipes/managed_san_set_public_attributes.rb

 17: oneview_managed_san 'ManagedSAN1' do
 18:   client node['oneview_test']['client']
 19:   data(
 20:     publicAttributes: [
 21:       {
 22:         name: 'MetaSan',
 23:         value: 'Neon SAN',
 24:         valueType: 'String',
 25:         valueFormat: 'None'
 26:       }
 27:     ]
 28:   )
 29:   action :set_public_attributes
 30: end

Compiled Resource:
------------------
# Declared in /var/folders/m_/whcml1ts22dbypfjlhnxjzrc0000gn/T/d20161011-23925-x4v49x/cookbooks/oneview_test/recipes/managed_san_set_public_attributes.rb:17:in `from_file'

oneview_managed_san("ManagedSAN1") do
  action [:set_public_attributes]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :oneview_managed_san
  cookbook_name :oneview_test
  recipe_name "managed_san_set_public_attributes"
  client {"url"=>"https://oneview.example.com", "user"=>"Administrator", "password"=>"secret123"}
  data {:publicAttributes=>[{:name=>"MetaSan", :value=>"Neon SAN", :valueType=>"String", :valueFormat=>"None"}]}
end

Platform:
---------
x86_64-darwin15
```

Is this considered ok? If i remember correctly there was a mock/stub out some of these things, has that gone or been removed?

**Comment by hdiomede** [comment]
The tests expect it to fail if does not exists and we are testing this in this first example

``` ruby
describe 'oneview_test::managed_san_set_public_attributes' do
  let(:resource_name) { 'managed_san' }
  include_context 'chef context'

  it 'fails whe it does not exist' do
    allow_any_instance_of(OneviewSDK::ManagedSAN).to receive(:exists?).and_return(false)
    expect { real_chef_run }.to raise_error(/Resource not found: oneview_managed_san 'ManagedSAN1'/)
  end
end
```

I don't know if this is ChefSpec simulating like it failed in a real chef run or what.

**Comment by jjasghar** [comment]
Ah, ok that makes sense.

I think the `exit 1`/failure is coming from:

```
Coverage report generated for RSpec to /var/lib/jenkins/workspace/oneview-cookbook/coverage. 901 / 2209 LOC (40.79%) covered.
Coverage (40.79%) is below the expected minimum coverage (98.00%).
/opt/rubies/ruby-2.3.1/bin/ruby -I/var/lib/jenkins/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/lib:/var/lib/jenkins/.gem/ruby/2.3.1/gems/rspec-support-3.5.0/lib /var/lib/jenkins/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*/\*_spec.rb --color  failed
```

Any advice here?

**Comment by hdiomede** [comment]
Looks like it is considering the sdk to generate the report.

https://jenkins-01.eastus.cloudapp.azure.com/job/oneview-cookbook/ws/coverage/index.html

**Comment by jjasghar** [comment]
Oh wow didn't even see that. Pretty neat. 

I'd love to see this green, though I'm not 100% sure what the best course of action here is.

**Comment by hdiomede** [comment]
I've just simulated the condition to check if our rakefile was somehow allowing rake to execute RSpec in parent directories but it worked.

Could you share info about the build process?

Btw, thank you very much for the help :D

**Comment by jjasghar** [comment]
sure, we have everything open sourced at: https://github.com/chef-partners/chef-partner-cookbook-program-jjb

and yall's are specifically:
- https://github.com/chef-partners/chef-partner-cookbook-program-jjb/blob/master/jobs/oneview-cookbook.yml
- https://github.com/chef-partners/chef-partner-cookbook-program-jjb/blob/master/jobs/ilo-cookbook.yml

PR's are more then accepted, and would love some feedback.

**Comment by jsmartt** [comment]
I think we can just add a line to ignore the .direnv directory in our spec_helper.rb to fix that issue. Working on that now...

**Comment by jjasghar** [comment]
@jsmartt i'm good with whatever :)

**Comment by jsmartt** [comment]
Opened a new PR (#78) since I can't push to JJ's fork.

**Pull request closed without merging**
