### PR TITLE
Datacenter implementation

### PR DESCRIPTION
**Pull request by hdiomede**

### CODE REVIEW

**Comment by jsmartt** [comment]
Looks good :smile: Can you add a section to the README though with the usage of this resource?

**Comment by hdiomede** [comment]
Of course, I forgot we were doing it.
Thanks!

**Comment by jsmartt** [comment]
Cool. And it's not necessarily specific to this PR/resource, but we have a few different places that examples live (README, the examples/ directory, and to an extent, the spec/fixtures/cookbooks/oneview_test/recipes directory).  I think it's fine; I really like having a few examples in the README, but putting a complete set of them in there would get crazy (hence the examples/ directory). I think we just need to put a link in the README to that and the test cookbook examples (and keep a pretty complete, well-commented set in the examples directory).

Just curious if you guys had any thoughts about it?

**Comment by hdiomede** [comment]
@jsmartt I've just created #15 to address this question

**Pull request merged**
